spring.application.name=poligon_backend

# OAuth2 - Google
spring.security.oauth2.client.registration.google.client-id=215092678726-jmfsobeui3fg09vl7o31jg4p5s3gun2a.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=https://jyhdevstore.store/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google

# OAuth2 - Kakao
spring.security.oauth2.client.registration.kakao.client-id=9ec5eac21fe90ab638d113e257811e51
spring.security.oauth2.client.registration.kakao.client-authentication-method=POST
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,account_email
spring.security.oauth2.client.registration.kakao.client-name=Kakao

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

spring.datasource.url=jdbc:mariadb://jinin000223.mycafe24.com:3306/jinin000223
spring.datasource.username=jinin000223
spring.datasource.password=qw12!34er

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
server.address=0.0.0.0

# ?? ?? ??
server.port=8080