spring:
  application:
    name: demo

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: [215092678726-jmfsobeui3fg09vl7o31jg4p5s3gun2a.apps.googleusercontent.com]
            client-secret: [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]
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
          kakao:
            client-id: 9ec5eac21fe90ab638d113e257811e51
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  #  테스트 DB 
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080
